language: python

python:
  - "2.7"

before_install:
  openssl aes-256-cbc -K $encrypted_4125254adb9a_key -iv $encrypted_4125254adb9a_iv -in deploy_rsa.enc -out ~\/deploy_rsa -d

install:
  - pip install fabric

script:
  fab -p ~/deploy_rsa update
  