language: python

python:
  - "2.7"

before_install:
  - openssl aes-256-cbc -K $encrypted_4125254adb9a_key -iv $encrypted_4125254adb9a_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

install:
  - pip install fabric

script:
  fab update
  