language: python

python:
  - "2.7"

before_install:
  - ENCRYPTED_KEY_VAR=$encrypted_4125254adb9a_key
  - ENCRYPTED_IV_VAR=$encrypted_4125254adb9a_iv
  - ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
  - ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}

  - openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

install:
  - pip install fabric

script:
  fab update
  